## Reading and writing CSV files with NumPy

In [8]:
# import genfromtxt function
from numpy import genfromtxt

# Read comma separated file
product_data = genfromtxt('demo.csv', delimiter=',')

# display initial 5 records
print(product_data)

[[14. 32. 33.]
 [24. 45. 26.]
 [27. 38. 39.]]


In [9]:
# import numpy
import numpy as np

# Create a sample array
sample_array = np.asarray([ [1,2,3], [4,5,6], [7,8,9] ])

# Write sample array to CSV file
np.savetxt("my_first_demo.csv", sample_array, delimiter=",")

## Reading and writing CSV files with Pandas

In [14]:
# import pandas
import pandas as pd

# Read CSV file
sample_df=pd.read_csv('demo.csv', sep=',' , header=None)

# display initial 5 records
sample_df.head()

0   1   2
0  14  32  33
1  24  45  26
2  27  38  39

In [15]:
# Save DataFrame to CSV file
sample_df.to_csv('demo_sample_df.csv')

## Reading and Writing Data from Excel

In [23]:
# Read excel file
df=pd.read_excel('employee.xlsx',sheet_name='performance')

# display initial 5 records
df.head()

name  performance_score
0    Allen Smith                723
1        S Kumar                520
2    Jack Morgan                674
3      Ying Chin                556
4  Dheeraj Patel                711

In [24]:
df.to_excel('employee_performance.xlsx')

In [29]:
# Read excel file
emp_df=pd.read_excel('employee.xlsx',sheet_name='employee_details')

In [30]:
# write multiple dataframes to single excel file
with pd.ExcelWriter('new_employee_details.xlsx') as writer:
    emp_df.to_excel(writer, sheet_name='employee')
    df.to_excel(writer, sheet_name='perfromance')

## Reading and Writing Data from JSON

In [33]:
# Reading JSON file
df=pd.read_json('employee.json')

# display initial 5 records
df.head()

name   age   income gender  department grade
0    Allen Smith  45.0      NaN   None  Operations    G3
1        S Kumar   NaN  16000.0      F     Finance    G0
2    Jack Morgan  32.0  35000.0      M     Finance    G2
3      Ying Chin  45.0  65000.0      F       Sales    G3
4  Dheeraj Patel  30.0  42000.0      F  Operations    G2

In [35]:
# Writing DataFrame to JSON file
df.to_json('employee_demo.json',orient="columns")

## Reading and Writing Data from HDF5

In [ ]:
# Write DataFrame to hdf5
df.to_hdf('employee.h5', 'table', append=True)

In [37]:
# Read a hdf5 file
df=pd.read_hdf('employee.h5', 'table')

# display initial 5 records
df.head()

name   age   income gender  department grade
0    Allen Smith  45.0      NaN    NaN  Operations    G3
1        S Kumar   NaN  16000.0      F     Finance    G0
2    Jack Morgan  32.0  35000.0      M     Finance    G2
3      Ying Chin  45.0  65000.0      F       Sales    G3
4  Dheeraj Patel  30.0  42000.0      F  Operations    G2

## Reading and Writing Data from HTML Tables

In [38]:
import pandas as pd

In [39]:
# Reading HTML table from given URL
table_url = 'https://en.wikipedia.org/wiki/List_of_sovereign_states_and_dependent_territories_in_North_America'
df_list = pd.read_html(table_url)
print("Number of DataFrames:",len(df_list))

Number of DataFrames: 8


In [42]:
# Check first DataFrame
print(df_list[0].head())

   Flag        English Short Name            English Long Name  \
0   NaN  Antigua and Barbuda[n 1]          Antigua and Barbuda   
1   NaN         Bahamas, The[n 1]  Commonwealth of The Bahamas   
2   NaN             Barbados[n 1]                     Barbados   
3   NaN          Belize[n 1][n 2]                       Belize   
4   NaN               Canada[n 3]                       Canada   

          Domestic Short Name(s)     Capital               Currency  
0   English: Antigua and Barbuda  St. John's  East Caribbean dollar  
1               English: Bahamas      Nassau        Bahamian dollar  
2              English: Barbados  Bridgetown       Barbadian dollar  
3                English: Belize    Belmopan          Belize dollar  
4  English: CanadaFrench: Canada      Ottawa        Canadian dollar  


In [41]:
# Write DataFrame to raw HTML
df_list[1].to_html('country.html')

## Reading and Writing Data from parquet

In [44]:
!pip install pyarrow

     |████████████████████████████████| 17.8 MB 143 kB/s eta 0:00:01


In [52]:
# Write to a parquet file.
df.to_parquet('employee.parquet', engine='pyarrow')

In [53]:
# Read parquet file
employee_df = pd.read_parquet('employee.parquet', engine='pyarrow')

# display initial 5 records
employee_df.head()

name   age   income gender  department grade
0    Allen Smith  45.0      NaN   None  Operations    G3
1        S Kumar   NaN  16000.0      F     Finance    G0
2    Jack Morgan  32.0  35000.0      M     Finance    G2
3      Ying Chin  45.0  65000.0      F       Sales    G3
4  Dheeraj Patel  30.0  42000.0      F  Operations    G2

## Reading and Writing Data from Pickle Pandas Object

In [54]:
# import pandas
import pandas as pd

# Read CSV file
df=pd.read_csv('demo.csv', sep=',' , header=None)

# Save DataFrame object in pickle file
df.to_pickle('demo_obj.pkl')

In [62]:
#Read DataFrame object from pickle file
pickle_obj=pd.read_pickle('demo_obj.pkl')

# display initial 5 records
pickle_obj.head()

0   1   2
0  14  32  33
1  24  45  26
2  27  38  39

## Lightweight access with sqllite3

In [ ]:
# Import sqlite3
import sqlite3

# Create connection. This will create the connection with employee database.
# If the database does not exist it will create the database
conn = sqlite3.connect('employee.db')

# Create cursor
cur = conn.cursor()

# Execute SQL query and create the database table
cur.execute("create table emp(eid int,salary int)")

# Execute SQL query and Write the data into database
cur.execute("insert into emp values(105, 57000)")

# commit the transaction
con.commit()

# Execute SQL query and Read the data from the database
cur.execute('select * from emp')

# Fetch records
print(cur.fetchall())

# Close the Database connection
conn.close()

## Reading and Writing Data from MySQL

In [ ]:
# import pymysql connector module
import pymysql

# Create a connection object using connect() method with parameters IP Address, user name, password, database name, character set and cursor type.

connection = pymysql.connect(host='localhost', # IP address of the MySQL database server
                             user='root', # user name
                             password='12345', # password
                             db='emp', # database name
                             charset='utf8mb4', # character set
                             cursorclass=pymysql.cursors.DictCursor) # cursor type

try:
    with connection.cursor() as cur:
        # Inject a record in database
        sql_query = "INSERT INTO `emp` (`eid`, `salary`) VALUES (%s, %s)"
        cur.execute(sql_query, (104,43000))


    # Execution will not commit records automatically. We need to commit the record insertion explicitly.
    connection.commit()

    with connection.cursor() as cur:
        # Read records from employee table
        sql_query = "SELECT * FROM `emp`"
        cur.execute(sql_query )
        table_data = cursor.fetchall()
        print(table_data)

except:
    print("Exception Occurred")
finally:
    connection.close()

In [ ]:
# Import the required connector
import mysql.connector

# Establish a database connection to mysql
connection=mysql.connector.connect(user='root',password='12345',host='localhost',database='employee')

# Create a cursor
cur=connection.cursor()

# Running sql query
cur.execute("select * from emp")

# Fetch all the records and print it one by one using for loop
for i in cur.fetchall():
    print(i)

# Create a DataFrame from fetched records.
df = pd.DataFrame(cur.fetchall())

# Assign column names to DataFrame
df.columns = [i[0] for i in cur.description]

# close the connection
connection.close()

In [ ]:
# Import the sqlalchemy engine
from sqlalchemy import create_engine

# Instantiate engine object
en = create_engine("mysql+pymysql://{user}:{pw}@localhost/{db}"
                .format(user="root", 
                        pw="abc@123", 
                        db="emp"))

# Insert the whole dataframe into the database using to_sql() with the table name, if_exists and chunksize parameter

df.to_sql('emp', con=en, if_exists='append',chunksize=1000)

## Reading and Writing Data from MongoDB

In [ ]:
!pip install pymongo

In [ ]:
# Import pymongo
import pymongo

# Create mongo client
client = pymongo.MongoClient()

# Get database
db = client.employee

# Get the collection from database
collection = db.emp

employee_salary = {"eid":114, "salary":25000}

# Write the data using insert_one() method
collection.insert_one(employee_salary)

# Read the data from collection and assigns fetched data to pandas DataFrame
data = pd.DataFrame(list(collection.find()))

## Reading and Writing Data from Cassandra

In [ ]:
!pip install cassandra-driver

In [ ]:
# Import the cluster
from cassandra.cluster import Cluster

# Creating a cluster object
cluster = Cluster()

# Create connections by calling Cluster.connect():
conn = cluster.connect()

# Execute the insert query
session.execute(
 """ INSERT INTO users (eid, ename, age) VALUES (%(eid)s, %(ename)s, %(age)s, %(name)s)""", 
 {'eid':101, 'ename': "Steve smith", 'age': 42})

# Execute the select query
rows = conn.execute('SELECT * FROM users')

# Print the results
for emp_row in rows:
    print(emp_row.eid, emp_row.ename, emp_row.age)

# Create a dataframe and assign fetched data to DataFrame
data = pd.DataFrame(rows)

## Reading and Writing Data from Redis

In [ ]:
!pip install redis

In [21]:
# Import module
import redis

# Create connection
r = redis.Redis(host='localhost', port=6379, db=0)

# Setting key-value pair
r.set('eid', '101')

# Get value for given key
value=r.get('eid')

# Print the value
print(value)

101


## Pony ORM

In [ ]:
!pip install pony

In [ ]:
# Import pony module
from pony.orm import *

# Create database
db = Database()

# Define entities
class Emp(db.Entity):
    eid = PrimaryKey(int,auto=True)
    salary = Required(int)

# Check entity definition
show(Emp)

# Bind entities to MySQL database
db.bind('mysql', host='localhost', user='root', passwd='12345', db='employee')

# Generate required mappings for entities
db.generate_mapping(create_tables=True)

# turn on the debug mode
sql_debug(True)

# Select the records from Emp entities or emp table
select(e for e in Emp)[:]

# Show the values of all the attribute
select(e for e in Emp)[:].show()